// Generated by CoffeeScript 1.6.3
/*
 # jQuery MrJared Scroll Slide v0.1
 #
 #
 # TERMS OF USE - MrJared Scroll Slide
 # 
 # Open source under the BSD License. 
 # 
 # Copyright © 2013 Rafael Jared Vásquez Montero
 # All rights reserved.
 # 
 # Redistribution and use in source and binary forms, with or without modification, 
 # are permitted provided that the following conditions are met:
 # 
 # Redistributions of source code must retain the above copyright notice, this list of 
 # conditions and the following disclaimer.
 # Redistributions in binary form must reproduce the above copyright notice, this list 
 # of conditions and the following disclaimer in the documentation and/or other materials 
 # provided with the distribution.
 # 
 # Neither the name of the author nor the names of contributors may be used to endorse 
 # or promote products derived from this software without specific prior written permission.
 # 
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 # EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 #  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 #  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 #  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
 # AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 #  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 # OF THE POSSIBILITY OF SUCH DAMAGE. 
 #
*/


/*Editar valores para controlar los deplazamientos y velocidade los mismos*/


(function() {
  var $;

  $ = jQuery;

  $.fn.MrJaredScrollSlide = function(options) {
    var defaults;
    defaults = {
      scrollwidth: 327,
      speed: 500
    };
    options = $.extend(defaults, options);
    return this.each(function() {
      var cantMax, elemento, pag;
      pag = 1;
      elemento = $(this);
      return cantMax = $(elemento).find('.pages .page').length - 3;
    });
  };

}).call(this);
